"""add is_staff

Revision ID: 18a5ac1032ed
Revises: e56cc10d7625
Create Date: 2026-08-09 16:17:30.496732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18a5ac1032ed"
down_revision: Union[str, None] = "e56cc10d7625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("is_staff", sa.Boolean(), nullable=False, server_default="false"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###
